<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
    <meta charset="UTF-8">
    <title>Pathfinder | Print Report</title>
    @vite(['resources/css/app.css'])
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body class="font-outfit p-5">
    <h1 class="text-center text-2xl font-bold mb-5">Pathfinder Student Employability Report: BSHM, BSIT, and BSCS Programs</h1>
    <div class="text-justify mb-8 space-y-4 leading-relaxed text-gray-700">
        <p>
           This comprehensive report presents the summarized findings and insights generated by the Pathfinder: 
           Career Assessment System, an advanced platform developed to evaluate and monitor student employability 
           and job recommendation across 3 different academic non-board programs. The system offers a detailed 
           overview of student performance, employability status, and other essential indicators derived from thorough 
           assessments and data-driven analytics. By examining personality traits, soft skills, academic achievements, personal experience, and skill scale 
           Pathfinder provides educators, administrators, and students with a clearer understanding of career 
           employability and professional growth. This analytical approach supports informed decision-making and 
           fosters continuous improvement within the institution, ensuring that students are fully prepared to 
           meet the evolving needs and expectations of the modern workforce.
        </p>
        
        <p>
           This report presents a statistical analysis focusing on the employability outcomes of students from three 
           non-board academic programs: Bachelor of Science in Hospitality Management (BSHM), Bachelor of Science in 
           Information Technology (BSIT), and Bachelor of Science in Computer Science (BSCS). In each program, 
           students are grouped into two categories based on comprehensive assessments, “employable” students who 
           have shown the skills, competencies, and qualifications that meet industry standards, and “not employable” 
           students who may still need further training, skill enhancement, or academic support to become job-ready.
        </p>
        
        <p>
           The visualizations in this report present a year-by-year overview of employability trends for each academic
           program, allowing a clear view of how employability rates change over time. By comparing the annual 
           distribution of employable and not employable students, administrators can identify patterns linked to 
           factors such as curriculum updates, shifts in industry demands, or the success of career development 
           initiatives.This long-term perspective is essential for determining whether existing strategies are 
           effective and for guiding data-driven improvements to academic programs. The individual analyses for 
           BSHM, BSIT, and BSCS acknowledge that each field has its own distinct skills, qualifications, and career 
           paths. As such, each program requires tailored approaches to better support student development and ensure 
           that graduates are fully equipped to thrive in their chosen professions.
        </p>
    </div>

    <!-- BSHM Section -->
    <p class="text-justify mt-30 mb-5">
        The bar graph below shows the statistics for the employable and not employable students in the Bachelor of 
        Science in Hospitality Management (BSHM) program. It presents the number of students who are considered 
        employable based on their skills and qualifications, as well as those who are not yet employable. This data 
        serves as a visual representation of the current employability status of BSHM students.
    </p>
    
    <div class="flex justify-center items-center p-4">
        <div class="bg-white border border-gray-200 rounded-sm shadow-sm p-6 w-[400px]">
            <h1 class="font-medium text-gray-700 text-center mb-4">Employable Students (BSHM)</h1>
            <div class="w-full" style="height: 250px;">
                <canvas id="bshmEmployableChart"></canvas>
            </div>
        </div>
    </div>

    <div class="flex justify-center items-center p-4 mb-20">
        <div class="bg-white border border-gray-200 rounded-sm shadow-sm p-6 w-[400px]">
            <h1 class="font-medium text-gray-700 text-center mb-4">Not Employable Students (BSHM)</h1>
            <div class="w-full" style="height: 250px;">
                <canvas id="bshmNotEmployableChart"></canvas>
            </div>
        </div>
    </div>

    <!-- BSIT Section -->
    <p class="text-justify mt-20 mb-5">
        The bar graph below shows the statistics for the employable and not employable students in the Bachelor of 
        Science in Information Technology (BSIT) program. It presents the number of students who are considered 
        employable based on their skills and qualifications, as well as those who are not yet employable. This data 
        serves as a visual representation of the current employability status of BSIT students.
    </p>
    
    <div class="flex justify-center items-center p-4">
        <div class="bg-white border border-gray-200 rounded-sm shadow-sm p-6 w-[400px]">
            <h1 class="font-medium text-gray-700 text-center mb-4">Employable Students (BSIT)</h1>
            <div class="w-full" style="height: 250px;">
                <canvas id="bsitEmployableChart"></canvas>
            </div>
        </div>
    </div>

    <div class="flex justify-center items-center p-4 mb-20">
        <div class="bg-white border border-gray-200 rounded-sm shadow-sm p-6 w-[400px]">
            <h1 class="font-medium text-gray-700 text-center mb-4">Not Employable Students (BSIT)</h1>
            <div class="w-full" style="height: 250px;">
                <canvas id="bsitNotEmployableChart"></canvas>
            </div>
        </div>
    </div>
    
    <!-- BSCS Section -->
    <p class="text-justify mt-20 mb-5">
        The bar graph below shows the statistics for the employable and not employable students in the Bachelor of 
        Science in Computer Science (BSCS) program. It presents the number of students who are considered 
        employable based on their skills and qualifications, as well as those who are not yet employable. This data 
        serves as a visual representation of the current employability status of BSCS students.
    </p>
    
    <div class="flex justify-center items-center p-4">
        <div class="bg-white border border-gray-200 rounded-sm shadow-sm p-6 w-[400px]">
            <h1 class="font-medium text-gray-700 text-center mb-4">Employable Students (BSCS)</h1>
            <div class="w-full" style="height: 250px;">
                <canvas id="bscsEmployableChart"></canvas>
            </div>
        </div>
    </div>

    <div class="flex justify-center items-center p-4">
        <div class="bg-white border border-gray-200 rounded-sm shadow-sm p-6 w-[400px]">
            <h1 class="font-medium text-gray-700 text-center mb-4">Not Employable Students (BSCS)</h1>
            <div class="w-full" style="height: 250px;">
                <canvas id="bscsNotEmployableChart"></canvas>
            </div>
        </div>
    </div>

    <!-- Predicted Employment Rate Section for All Programs -->
    <p class="text-justify mt-20 mb-5">
        The line graph below illustrates the average predicted employment rate across the three programs - 
        Bachelor of Science in Hospitality Management (BSHM), Bachelor of Science in Information Technology (BSIT), 
        and Bachelor of Science in Computer Science (BSCS) - tracked over several academic years. This metric 
        reflects the estimated percentage of graduates from these programs who are likely to find employment in 
        their respective fields within a certain period after graduation. By combining data from all three programs, 
        the visualization offers a comprehensive picture of overall graduate employability, helping institutional 
        leaders evaluate how well career preparation efforts, curriculum design, and academic support align with 
        industry demands. The trend shown in the graph highlights whether graduate employment opportunities are 
        improving, stable, or declining over time, providing valuable insights that can guide strategic decisions, 
        enhance academic programs, and strengthen institutional efforts to help students succeed in their chosen 
        careers.
    </p>

    <div class="flex justify-center items-center p-4 mb-10">
        <div class="bg-white border border-gray-200 rounded-sm shadow-sm p-6 w-[600px]">
            <h1 class="font-medium text-gray-700 text-center mb-4">Average Predicted Employment Rate (BSHM, BSIT & BSCS)</h1>
            <div class="w-full" style="height: 350px;">
                <canvas id="allProgramsEmploymentRateChart"></canvas>
            </div>
        </div>
    </div>

    <script>
        // Parse data from Laravel
        const bshmData = @json($bshmEmployabilityPerYear);
        const bsitData = @json($bsitEmployabilityPerYear);
        const bscsData = @json($bscsEmployabilityPerYear);
        const allProgramsData = @json($allProgramsEmploymentRate);

        // Wait for page to fully load
        window.addEventListener('load', function() {
            // ========== BSHM Charts ==========
            const bshmYears = bshmData.map((item) => item.year);
            const bshmEmployableCounts = bshmData.map((item) => item.employable_count);
            const bshmNotEmployableCounts = bshmData.map((item) => item.not_employable_count);

            const bshmEmployableChart = document.getElementById("bshmEmployableChart");
            if (bshmEmployableChart) {
                new Chart(bshmEmployableChart, {
                    type: "bar",
                    data: {
                        labels: bshmYears,
                        datasets: [{
                            label: "Employable Students",
                            data: bshmEmployableCounts,
                            backgroundColor: "rgba(75, 192, 192, 0.6)",
                            borderColor: "rgb(75, 192, 192)",
                            borderWidth: 2,
                        }],
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                display: true,
                                position: 'top',
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                ticks: {
                                    stepSize: 1,
                                },
                            },
                        },
                    },
                });
            }

            const bshmNotEmployableChart = document.getElementById("bshmNotEmployableChart");
            if (bshmNotEmployableChart) {
                new Chart(bshmNotEmployableChart, {
                    type: "bar",
                    data: {
                        labels: bshmYears,
                        datasets: [{
                            label: "Not Employable Students",
                            data: bshmNotEmployableCounts,
                            backgroundColor: "rgba(255, 99, 132, 0.6)",
                            borderColor: "rgb(255, 99, 132)",
                            borderWidth: 2,
                        }],
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                display: true,
                                position: 'top',
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                ticks: {
                                    stepSize: 1,
                                },
                            },
                        },
                    },
                });
            }

            // ========== BSIT Charts ==========
            const bsitYears = bsitData.map((item) => item.year);
            const bsitEmployableCounts = bsitData.map((item) => item.employable_count);
            const bsitNotEmployableCounts = bsitData.map((item) => item.not_employable_count);

            const bsitEmployableChart = document.getElementById("bsitEmployableChart");
            if (bsitEmployableChart) {
                new Chart(bsitEmployableChart, {
                    type: "bar",
                    data: {
                        labels: bsitYears,
                        datasets: [{
                            label: "Employable Students",
                            data: bsitEmployableCounts,
                            backgroundColor: "rgba(54, 162, 235, 0.6)",
                            borderColor: "rgb(54, 162, 235)",
                            borderWidth: 2,
                        }],
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                display: true,
                                position: 'top',
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                ticks: {
                                    stepSize: 1,
                                },
                            },
                        },
                    },
                });
            }

            const bsitNotEmployableChart = document.getElementById("bsitNotEmployableChart");
            if (bsitNotEmployableChart) {
                new Chart(bsitNotEmployableChart, {
                    type: "bar",
                    data: {
                        labels: bsitYears,
                        datasets: [{
                            label: "Not Employable Students",
                            data: bsitNotEmployableCounts,
                            backgroundColor: "rgba(255, 159, 64, 0.6)",
                            borderColor: "rgb(255, 159, 64)",
                            borderWidth: 2,
                        }],
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                display: true,
                                position: 'top',
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                ticks: {
                                    stepSize: 1,
                                },
                            },
                        },
                    },
                });
            }

            // ========== BSCS Charts ==========
            const bscsYears = bscsData.map((item) => item.year);
            const bscsEmployableCounts = bscsData.map((item) => item.employable_count);
            const bscsNotEmployableCounts = bscsData.map((item) => item.not_employable_count);

            const bscsEmployableChart = document.getElementById("bscsEmployableChart");
            if (bscsEmployableChart) {
                new Chart(bscsEmployableChart, {
                    type: "bar",
                    data: {
                        labels: bscsYears,
                        datasets: [{
                            label: "Employable Students",
                            data: bscsEmployableCounts,
                            backgroundColor: "rgba(153, 102, 255, 0.6)",
                            borderColor: "rgb(153, 102, 255)",
                            borderWidth: 2,
                        }],
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                display: true,
                                position: 'top',
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                ticks: {
                                    stepSize: 1,
                                },
                            },
                        },
                    },
                });
            }

            const bscsNotEmployableChart = document.getElementById("bscsNotEmployableChart");
            if (bscsNotEmployableChart) {
                new Chart(bscsNotEmployableChart, {
                    type: "bar",
                    data: {
                        labels: bscsYears,
                        datasets: [{
                            label: "Not Employable Students",
                            data: bscsNotEmployableCounts,
                            backgroundColor: "rgba(255, 205, 86, 0.6)",
                            borderColor: "rgb(255, 205, 86)",
                            borderWidth: 2,
                        }],
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                display: true,
                                position: 'top',
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                ticks: {
                                    stepSize: 1,
                                },
                            },
                        },
                    },
                });
            }

            // ========== All Programs Employment Rate Chart ==========
            const allProgramsYears = allProgramsData.map((item) => item.year);
            const allProgramsRates = allProgramsData.map((item) => parseFloat(item.average_rate).toFixed(2));

            const allProgramsChart = document.getElementById("allProgramsEmploymentRateChart");
            if (allProgramsChart) {
                new Chart(allProgramsChart, {
                    type: "line",
                    data: {
                        labels: allProgramsYears,
                        datasets: [{
                            label: "Average Predicted Employment Rate (%)",
                            data: allProgramsRates,
                            fill: true,
                            backgroundColor: "rgba(139, 92, 246, 0.1)",
                            borderColor: "rgb(139, 92, 246)",
                            borderWidth: 3,
                            tension: 0.4,
                            pointBackgroundColor: "white",
                            pointBorderColor: "rgb(139, 92, 246)",
                            pointBorderWidth: 2,
                            pointRadius: 6,
                            pointHoverRadius: 8,
                        }],
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                            legend: {
                                display: true,
                                position: 'top',
                            }
                        },
                        scales: {
                            y: {
                                beginAtZero: true,
                                max: 100,
                                ticks: {
                                    callback: function (value) {
                                        return value + "%";
                                    },
                                    stepSize: 10,
                                },
                                grid: {
                                    color: 'rgba(0, 0, 0, 0.1)'
                                }
                            },
                            x: {
                                grid: {
                                    display: false
                                }
                            }
                        },
                    },
                });
            }

            // Print after charts are rendered
            setTimeout(() => {
                window.print();
            }, 1500);
        });
    </script>
</body>
</html>